# Generated by Django 6.0.3 on 2026-06-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_store_owner_alter_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='رقم الفاتورة')),
                ('billing_year', models.PositiveIntegerField(verbose_name='السنة')),
                ('billing_month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المبيعات')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='نسبة العمولة')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العمولة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الدفع'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.store', verbose_name='المتجر')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'billing_year', 'billing_month'), name='unique_monthly_invoice')],
            },
        ),
    ]
