# Generated by Django 6.0.3 on 2026-06-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='value',
            new_name='commission_value',
        ),
    ]
