# Generated by Django 6.0.3 on 2026-06-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_store_owner_alter_userprofile_name'),
        ('management', '0002_rename_value_recipe_commission_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نسبة العمولة'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.store', verbose_name='المتجر'),
        ),
    ]
