# Generated by Django 6.0.3 on 2026-09-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_recipe_commission_rate_alter_recipe_store'),
        ('orders', '0011_alter_order_customer_name_alter_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_monthly_invoice',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
