# Generated by Django 6.0.3 on 2026-04-19 12:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_vendor_permission_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='قم بإدخال اسم المنتج', max_length=255, verbose_name='اسم المنتج')),
                ('thumbnail_img', models.ImageField(upload_to='vendors/Products/thumbnails', verbose_name='صورة المنتج الرئيسية')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='الوصف')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('show', models.BooleanField(default=False, help_text='قم بالأختيار ان كنت ترغب بعرض المنتج للزبائن مباشرة \n ان لم تقم بتحديده سيتم إخفاء المنتج ولن يتمكن زبائنك من رؤيته', verbose_name='عرض للزبائن')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='أدخل سعر الجملة الذي اشتريت به المنتج', max_digits=10, verbose_name='سعر الشراء')),
                ('price', models.DecimalField(decimal_places=2, help_text='أدخل سعر البيع النهائي للمنتج ', max_digits=10, verbose_name='سعر البيع')),
                ('offer', models.BooleanField(default=False, help_text='قم بتحديد هذا الخيار في حال كان المنتج عليه عرض تخفيض', verbose_name='تخفيض')),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, help_text='أدخل سعر التخفيض الخاص بالمنتج', max_digits=10, verbose_name='السعر بعد التخفيض')),
                ('free_delivery', models.BooleanField(default=False, help_text='قم بتحديد هذا الخيار في حال كنت تقدم خدمة التوصيل المجاني لهذا المنتج', verbose_name='توصيل مجاني')),
                ('total_sales', models.PositiveIntegerField(default=0, help_text='اجمالي عدد مرات بيع المنتج', verbose_name='عدد المبيعات')),
                ('status', models.CharField(choices=[('checking', 'جاري المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='checking', max_length=20, verbose_name='حالة المنتج')),
                ('rejected_cause', models.TextField(blank=True, help_text='في حال تم رفض المنتج،سيتم عرض سبب الرفض هنا', null=True, verbose_name='سبب الرفض')),
                ('has_sizes', models.BooleanField(default=True, help_text='قم بالتحديد ان كان المنتج الخاص بك له عدة مقاسات', verbose_name='المنتج له مقاسات')),
                ('type', models.CharField(choices=[('clothes', 'ملابس'), ('watches', 'ساعات'), ('Accessories', 'اكسسوارات')], verbose_name='نوع المنتج')),
                ('gender', models.CharField(choices=[('male', 'رجالي'), ('female', 'نسائي'), ('unisex', 'كلا الجنسين')], default='unisex', help_text='حدد إن كان المنتج موجّه للرجال أو النساء أو مناسب لكلا الجنسين', max_length=20, verbose_name='الجنس المستهدف')),
                ('max_quantity_per_order', models.PositiveIntegerField(default=10, help_text='حدد الحد الأقصى لعدد القطع التي يمكن للزبون طلبها من هذا المنتج في طلب واحد', verbose_name='الكمية القصوى للطلب')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.store')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(default=1, verbose_name='الرقم التسلسلي')),
                ('verification_status', models.CharField(choices=[('checking', 'جاري التحقق'), ('approved', 'طلب حقيقي'), ('rejected', 'طلب وهمي')], default='checking', max_length=20, verbose_name='حالة التحقق')),
                ('status', models.CharField(choices=[('processing', 'جاري التجهيز'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='processing', max_length=20, verbose_name='حالة الطلب')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('product_color', models.CharField(max_length=100, verbose_name='لون المنتج')),
                ('product_size', models.CharField(max_length=100, null=True, verbose_name='مقاس المنتج')),
                ('product_qty', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('purchase_price', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('free_delivery', models.BooleanField(default=False, verbose_name='توصيل مجاني')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم الزبون')),
                ('customer_phone', models.CharField(max_length=100, verbose_name='رقم هاتف الزبون')),
                ('customer_location', models.CharField(max_length=100, verbose_name='عنوان الزبون')),
                ('note', django_ckeditor_5.fields.CKEditor5Field(verbose_name='ملاحظة')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.store', verbose_name='المتجر')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='اللون')),
                ('image', models.ImageField(help_text='يمكنك إضافة صورة للون المنتج لتسهيل تمييزه من قبل الزبائن', null=True, upload_to='store/Products/colors/', verbose_name='الصورة')),
                ('available', models.BooleanField(default=True, help_text='قم بتحديد هذا الخيار في حال كان هذا اللون متوفر حاليا في المخزون \n ان لم تقم بتحديده سيتم إخفاء هذا اللون ولن يتمكن زبائنك من رؤيته \n في حال عدم توفر هذا اللون سيتم ايضا اخفاء جميع المقاسات المرتبطة به', verbose_name='متوفر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'لون المنتج',
                'verbose_name_plural': 'ألوان المنتج',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/Products/images', verbose_name='الصورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتج',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='قم بإدخال المقاس الخاص بالمنتج مثل S أو M أو L أو 40 أو 41 أو أي مقاس آخر يتناسب مع نوع المنتج', max_length=10, verbose_name='المقاس')),
                ('available', models.BooleanField(default=True, help_text='قم بتحديد هذا الخيار في حال كان هذا المقاس متوفر حاليا في المخزون \n ان لم تقم بتحديده سيتم إخفاء هذا المقاس ولن يتمكن زبائنك من رؤيته ', verbose_name='متوفر')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.productcolor', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مقاس المنتج',
                'verbose_name_plural': 'مقاسات المنتج',
            },
        ),
    ]
