# Generated by Django 6.0.3 on 2026-04-28 15:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='قم بإدخال وصف وتفاصيل المنتج ', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_img',
            field=models.ImageField(help_text='قم بإدخال صورة المنتج الرئيسية التي ستظهر في صفحة المتجر وصفحة تفاصيل المنتج', upload_to='vendors/Products/thumbnails', verbose_name='صورة المنتج الرئيسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothes', 'ملابس'), ('watches', 'ساعات'), ('Accessories', 'اكسسوارات')], default='clothes', help_text='قم بإختيار نوع المنتج الخاص بك', verbose_name='نوع المنتج'),
        ),
    ]
