# Generated by Django 6.0.3 on 2026-04-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='حدد الأولوية للصورة في عرض المنتج', verbose_name='الأولوية'),
        ),
    ]
