# Generated by Django 6.0.3 on 2026-05-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimages_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
