# Generated by Django 6.0.3 on 2026-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=True, help_text='قم بالتحديد ان كان المنتج الخاص بك له عدة مقاسات', verbose_name='المنتج له مقاسات'),
        ),
    ]
