# Generated by Django 6.0.3 on 2026-05-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
