# Generated by Django 6.0.3 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_img',
            field=models.ImageField(help_text='قم بإدخال صورة المنتج الرئيسية التي ستظهر في صفحة المتجر وصفحة تفاصيل المنتج', upload_to='store/Products/thumbnails', verbose_name='صورة المنتج الرئيسية'),
        ),
    ]
