# Generated by Django 6.0.3 on 2026-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_thumbnail_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show',
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(choices=[(True, 'معروض'), (False, 'مخفي')], default=False, help_text='قم بالأختيار ان كنت ترغب بعرض المنتج للزبائن مباشرة \n ان لم تقم بتحديده سيتم إخفاء المنتج ولن يتمكن زبائنك من رؤيته', verbose_name='عرض للزبائن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_quantity_per_order',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='حدد الحد الأقصى لعدد القطع التي يمكن للزبون طلبها من هذا المنتج في طلب واحد', verbose_name='الكمية القصوى للطلب'),
        ),
    ]
