# Generated by Django 6.0.3 on 2026-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_show_product_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(choices=[(True, 'ظاهر'), (False, 'مخفي')], default=False, help_text='قم بالأختيار ان كنت ترغب بإظهار المنتج للزبائن مباشرة \n ان لم تقم بتحديده سيتم إخفاء المنتج ولن يتمكن زبائنك من رؤيته', verbose_name='الظهور للزبائن'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
