# Generated by Django 6.0.3 on 2026-05-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_is_visible_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='available',
        ),
    ]
