# Generated by Django 6.0.3 on 2026-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_productsize_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rejected_cause',
            field=models.TextField(blank=True, help_text='في حال تم رفض المنتج، يرجى توضيح سبب الرفض هنا ليتسنى للبائع معرفة التعديلات المطلوبة لإعادة رفع المنتج للمراجعة مرة أخرى', null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('checking', 'جاري المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='checking', help_text='جاري المراجعة: تم رفع المنتج وسيتم مراجعته من قبل الإدارة خلال 24 ساعة | مقبول: تم قبول المنتج وهو ظاهر للزبائن | مرفوض: تم رفض المنتج لعدم مطابقته لمعايير الجودة أو لأي سبب آخر،', max_length=20, verbose_name='حالة المنتج'),
        ),
    ]
