# Generated by Django 6.0.3 on 2026-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_updated_at_alter_product_rejected_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(choices=[(False, 'مخفي'), (True, 'ظاهر')], default=True, help_text='قم بالأختيار ان كنت ترغب بإظهار المنتج للزبائن مباشرة \n ان لم تقم بتحديده سيتم إخفاء المنتج ولن يتمكن زبائنك من رؤيته', verbose_name='حالة الظهور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='قم بإدخال اسم المنتج', max_length=50, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='أدخل سعر الجملة الذي اشتريت به المنتج', max_digits=10, verbose_name='سعر التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothes', 'ملابس'), ('watches', 'ساعات'), ('accessories', 'اكسسوارات'), ('other', 'اخرى')], default='clothes', help_text='قم بإختيار نوع المنتج الخاص بك', verbose_name='نوع المنتج'),
        ),
    ]
