# Generated by Django 6.0.3 on 2026-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
    ]
