# Generated by Django 6.0.3 on 2026-04-12 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(help_text='قم بإدخال اسم المتجر', max_length=255, verbose_name='اسم المتجر')),
                ('status', models.CharField(choices=[('pending', 'قيد  المراجعة'), ('active', 'مُفعل'), ('inactive', 'غير مُفعل')], default='pending', max_length=20, verbose_name='حالة المتجر')),
                ('logo', models.ImageField(upload_to='vendors/Stores/logos', verbose_name='صورة لوجو المتجر')),
                ('location', models.CharField(help_text='قم بإدخال موقع المتجر الخاص بك \n يمكنك كتابة اسم المدينة فقط أو العنوان الكامل حسب رغبتك', max_length=255, verbose_name='الموقع')),
                ('telegram', models.CharField(help_text='قم بإدخال رقم التليجرام الخاص بالمتجر حيث سوف يتم ارسال التنبيهات الخاصة بمتجرك من خلاله', max_length=20, verbose_name='رقم التليجرام')),
                ('facebook', models.URLField(blank=True, help_text='قم بإدخال رابط بروفايل صفحة الفيسبوك الخاصة بمتجرك', verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, help_text='قم بإدخال رابط بروفايل صفحة الانستاجرام الخاصة بمتجرك', verbose_name='انستاجرام')),
                ('tiktok', models.URLField(blank=True, help_text='قم بإدخال رابط صفحة تيكتوك الخاصة بمتجرك', verbose_name='تيكتوك')),
                ('whatsapp', models.CharField(blank=True, help_text='قم بإدخال رقم الواتساب الخاص بالمتجر', max_length=20, verbose_name='رقم الواتساب')),
                ('phone_number1', models.CharField(help_text='قم بإدخال رقم الهاتف الذي تريد من الزبائن الاتصال بك من خلاله', max_length=20, null=True, verbose_name='رقم الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'إدارة'), ('vendor', 'بائع')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='قم بإدخال اسم المستخدم الخاص بك', max_length=255, verbose_name='اسم المستخدم')),
                ('permission_level', models.CharField(choices=[('view', 'عرض فقط'), ('edit', 'عرض وتعديل'), ('full', 'تحكم كامل (عرض + تعديل + حذف)')], default='view', help_text='قم بتحديد مستوى الصلاحية الخاص بك \n  عرض فقط: يمكنك عرض المنتجات والطلبات ولكن لا يمكنك تعديلها أو حذفها \n عرض وتعديل: يمكنك عرض وتعديل المنتجات والطلبات ولكن لا يمكنك حذفها \n  تحكم كامل: يمكنك عرض وتعديل وحذف المنتجات والطلبات والأرباح', max_length=20, verbose_name='مستوى الصلاحيات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='accounts.store', verbose_name='المتجر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
