# Generated by Django 6.0.3 on 2026-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'متجر', 'verbose_name_plural': 'المتاجر'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'بائع', 'verbose_name_plural': 'البائعين'},
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='default/default_store_logo.png', upload_to='vendors/Stores/logos', verbose_name='صورة لوجو المتجر'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram',
            field=models.CharField(blank=True, help_text='قم بإدخال رقم التليجرام الخاص بالمتجر حيث سوف يتم ارسال التنبيهات الخاصة بمتجرك من خلاله', max_length=20, verbose_name='رقم التليجرام'),
        ),
        migrations.AlterField(
            model_name='store',
            name='whatsapp',
            field=models.CharField(help_text='قم بإدخال رقم الواتساب الخاص بمتجرك حيث سنقوم بتفعيل حسابك من خلاله', max_length=20, verbose_name='رقم الواتساب'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='قم بإدخال اسمك الثنائي (الاسم الأول والاسم الأخير)', max_length=255, verbose_name='الاسم الثنائي'),
        ),
    ]
