# Generated by Django 6.0.3 on 2026-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_store_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number1',
            field=models.CharField(blank=True, help_text='قم بإدخال رقم الهاتف الذي تريد من الزبائن الاتصال بك من خلاله', max_length=20, verbose_name='رقم الاتصال'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
