# Generated by Django 6.0.3 on 2026-04-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_store_phone_number1_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='telegram',
            field=models.CharField(blank=True, help_text='قم بإدخال رقم التليجرام الخاص بالمتجر حيث سوف يتم ارسال التنبيهات الخاصة بمتجرك من خلاله', max_length=20, verbose_name='معرف التليجرام'),
        ),
    ]
