# Generated by Django 6.0.3 on 2026-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_store_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='permission_level',
            field=models.CharField(choices=[('view', 'عرض فقط'), ('edit', 'عرض وتعديل'), ('full', 'تحكم كامل (عرض + تعديل + حذف)'), ('owner', 'مالك المتجر')], default='view', help_text='قم بتحديد مستوى الصلاحية الخاص بك \n  عرض فقط: يمكنك عرض المنتجات والطلبات ولكن لا يمكنك تعديلها أو حذفها \n عرض وتعديل: يمكنك عرض وتعديل المنتجات والطلبات ولكن لا يمكنك حذفها \n  تحكم كامل: يمكنك عرض وتعديل وحذف المنتجات والطلبات والأرباح \n مالك المتجر : بإمكانه التحكم بكل شيء', max_length=20, verbose_name='مستوى الصلاحيات'),
        ),
    ]
