# Generated by Django 6.0.3 on 2026-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vendor_permission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number1',
            field=models.CharField(help_text='قم بإدخال رقم الهاتف الخاص بمتجرك (ملاحظة : سوف نقوم بالتواصل معك على واتساب لتفعيل حسابك) ', max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
