# Generated by Django 6.0.3 on 2026-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_store_whatsapp_alter_store_phone_number1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number1',
            field=models.CharField(help_text='قم بإدخال رقم الهاتف الخاص بمتجرك (ملاحظة : يجب ان يكون الرقم مربوطاً بواتساب لأننا سوف نقوم بالتواصل معك على واتساب لتفعيل حسابك) ', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, help_text=' اسم المتجر باللغة الانجليزية وبدون فراغات ', max_length=100, verbose_name='slug'),
        ),
    ]
