# Generated by Django 6.0.3 on 2026-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='permission_level',
            field=models.CharField(choices=[('edit', 'عرض وتعديل'), ('full', 'تحكم كامل (عرض + تعديل + حذف)'), ('owner', 'مالك المتجر')], default='edit', help_text='قم بتحديد مستوى الصلاحية الخاص بك \n عرض وتعديل: يمكنك عرض وتعديل المنتجات والطلبات ولكن لا يمكنك حذفها \n  تحكم كامل: يمكنك عرض وتعديل وحذف المنتجات والطلبات والأرباح \n مالك المتجر : بإمكانه التحكم بكل شيء', max_length=20, verbose_name='مستوى الصلاحيات'),
        ),
    ]
