# Generated by Django 6.0.3 on 2026-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_vendor_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='check_orders',
            field=models.BooleanField(choices=[(False, 'غير مُفعل'), (True, 'مُفعل')], default=True, help_text='في حال التفعيل سيقوم احد الموظفين لدينا من الاتصال بالزبون والتأكد من الطلب قبل ارسال اشعار اليك مما يقلل من الطلبات الوهمية', verbose_name='تحقق من الطلبات '),
        ),
    ]
