# Generated by Django 6.0.3 on 2026-05-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_store_check_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
    ]
