# Generated by Django 6.0.3 on 2026-06-19 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_store_owner_userprofile_name_delete_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='مالك المتجر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text='أدخل الاسم الأول والاسم الأخير', max_length=255, verbose_name='الاسم الثنائي'),
        ),
    ]
