# Generated by Django 6.0.3 on 2026-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_store_owner_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, help_text='قم بإدخال موقع المتجر الخاص بك \n يمكنك كتابة اسم المدينة فقط أو العنوان الكامل حسب رغبتك', max_length=100, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='قم بإدخال اسم المتجر', max_length=30, verbose_name='اسم المتجر'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number1',
            field=models.CharField(help_text='قم بإدخال رقم الهاتف الخاص بمتجرك (ملاحظة : يجب ان يكون الرقم مربوطاً بواتساب لأننا سوف نقوم بالتواصل معك على واتساب لتفعيل حسابك) ', max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text='أدخل الاسم الأول والاسم الأخير', max_length=20, verbose_name='الاسم الثنائي'),
        ),
    ]
