# Generated by Django 6.0.3 on 2026-05-08 17:58

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_vendor_permission_level'),
        ('store', '0009_alter_product_is_visible_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(default=1, verbose_name='الرقم التسلسلي')),
                ('verification_status', models.CharField(choices=[('checking', 'جاري التحقق'), ('approved', 'طلب حقيقي'), ('rejected', 'طلب وهمي')], default='checking', max_length=20, verbose_name='حالة التحقق')),
                ('status', models.CharField(choices=[('processing', 'جاري التجهيز'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='processing', max_length=20, verbose_name='حالة الطلب')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='توصيل مجاني')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم الزبون')),
                ('customer_phone', models.CharField(max_length=100, verbose_name='رقم هاتف الزبون')),
                ('customer_location', models.CharField(max_length=100, verbose_name='عنوان الزبون')),
                ('note', django_ckeditor_5.fields.CKEditor5Field(verbose_name='ملاحظة')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
            },
        ),
        migrations.CreateModel(
            name='OredrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/OrderItems/', verbose_name='صورة المنتج ')),
                ('color', models.CharField(max_length=100, verbose_name='لون المنتج')),
                ('size', models.CharField(max_length=100, null=True, verbose_name='مقاس المنتج')),
                ('qty', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='سعر الشراء')),
                ('selling_price', models.PositiveIntegerField(verbose_name='سعر البيع')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج للطلب',
                'verbose_name_plural': 'منتجات للطلب',
            },
        ),
    ]
