# Generated by Django 6.0.3 on 2026-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_oredritem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(choices=[(True, 'مجاني'), (False, 'غير مجاني')], default=False, verbose_name='توصيل مجاني'),
        ),
    ]
