# Generated by Django 6.0.3 on 2026-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_free_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverey_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم'),
        ),
    ]
