# Generated by Django 6.0.3 on 2026-05-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_deliverey_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliverey_date',
            new_name='delivery_date',
        ),
    ]
