# Generated by Django 6.0.3 on 2026-06-12 18:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_deliverey_date_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_location',
            field=models.CharField(help_text='أدخل عنوان التوصيل ، مثل: بنغازي - السلماني .', max_length=100, verbose_name='عنوان الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='أدخل الاسم الكامل للزبون، مثل: محمد أحمد.', max_length=100, verbose_name='اسم الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(help_text='أدخل رقم هاتف الزبون، مثل: 0912345678.', max_length=100, verbose_name='رقم هاتف الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(choices=[(True, 'مجاني'), (False, 'غير مجاني')], default=False, help_text='حدد ما إذا كان هذا الطلب مشمولًا بالتوصيل المجاني أم لا.', verbose_name='قيمة التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='يمكنك إضافة ملاحظات خاصة بالطلب، مثل تعليمات التوصيل أو طلبات خاصة من الزبون.', null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'جاري التجهيز'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='processing', help_text='حالة الطلب: جاري التجهيز:الطلب قيد المراجعة و التجهيز | تم التسليم: تم تسليم الطلب للزبون | ملغي: تم إلغاء الطلب من قبل الزبون أو المتجر', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
