# Generated by Django 6.0.3 on 2026-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_updated_at_alter_order_customer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.IntegerField(default=0, help_text='الربح المحقق من الطلب، محسوبًا كفرق بين إجمالي سعر البيع وإجمالي سعر الشراء.', verbose_name='الربح'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_purchase_price',
            field=models.PositiveIntegerField(default=0, help_text='إجمالي تكلفة المنتجات في الطلب، محسوبة بناءً على أسعار الشراء لكل منتج والكمية المطلوبة.', verbose_name='إجمالي سعر الشراء'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_selling_price',
            field=models.PositiveIntegerField(default=0, help_text='إجمالي سعر البيع للطلب، محسوبة بناءً على أسعار البيع لكل منتج والكمية المطلوبة.', verbose_name='إجمالي سعر البيع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='verification_status',
            field=models.CharField(choices=[('checking', 'جاري التحقق'), ('approved', 'طلب حقيقي'), ('rejected', 'طلب وهمي')], default='checking', help_text='حالة التحقق من الطلب: جاري التحقق: الطلب لم يتم التحقق منه بعد | طلب حقيقي: تم التحقق من صحة الطلب | طلب وهمي: تم رفض الطلب لعدم صحته', max_length=20, verbose_name='حالة التحقق'),
        ),
    ]
