# Generated by Django 6.0.3 on 2026-06-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_profit_order_total_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='profit',
            new_name='total_profit',
        ),
    ]
