# Generated by Django 6.0.3 on 2026-06-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_profit_order_total_profit'),
        ('store', '0011_product_updated_at_alter_product_rejected_cause_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrItem',
            new_name='OrderItem',
        ),
    ]
