# Generated by Django 6.0.3 on 2026-09-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('orders', '0010_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='أدخل الاسم الكامل للزبون، مثل: محمد أحمد.', max_length=20, verbose_name='اسم الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(help_text='أدخل رقم هاتف الزبون، مثل: 0912345678.', max_length=15, verbose_name='رقم هاتف الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'جاري التجهيز'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='processing', help_text='. عند تسليم المنتج للزبون، غيّر الحالة إلى تم التسليم ليتم تحديث إجمالي المبيعات والإحصائيات . إذا قام الزبون بإلغاء الطلب ، فغيّر الحالة إلى تم الإلغاء.', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
